version: '3'
services:
  backend:
    build: ./Cin-Manager/dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://localhost:27017/cinemaManger
    volumes:
      - ./Cin-Manager/:/app
    depends_on:
      - mongo

  frontend:
    build: ./dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
